"""add password_hash field

Revision ID: 415727681444
Revises: ca0161b7be38
Create Date: 2019-01-10 13:59:32.994698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415727681444'
down_revision = 'ca0161b7be38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
